In [1]:
#Question 1: #Print details of most viewed videos on YouTube from Wikipedia

In [34]:
#14/01
#import all the required libraries
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from webdriver_manager.chrome import ChromeDriverManager

pd.options.display.max_colwidth = 200

#Initializing selenium webdriver

options = webdriver.ChromeOptions()
#we use chromedriver manager to reduce chance of errors due to mismatched chrome version
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.maximize_window()

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST driver version for 97.0.4692
Driver [C:\Users\Neil\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache

In [2]:
#14/01
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos/'
driver.get(url) #load the webpage
driver.implicitly_wait(4) # wait while page loads
# navigating to the required web page
driver.get(driver.find_element_by_xpath("/html/body/div[3]/div[3]/div[5]/div[1]/table/tbody/tr/td/span/a").get_attribute('href'))
driver.get(driver.find_element_by_xpath("//*[@id='mw-content-text']/div[3]/ul/li[1]/div[1]/a").get_attribute('href'))

#creating and populating the variables 
video_rank = driver.find_elements_by_xpath("//table[3]//td[1]")
Video_Rank_List = []
for rank in video_rank[:30]:
    temp_rank = rank.text[:-1]
    Video_Rank_List.append(temp_rank)
    #print(rank.text)
#print(len(Video_Rank_List))

#video_name = driver.find_elements_by_xpath("//td[2]/a[1]")
video_name = driver.find_elements_by_xpath("//table[3]//td[2]")
Video_Name_List = []
for name in video_name[:30]:
    temp_name = name.text[:-4]
    #print(temp_name)
    Video_Name_List.append(temp_name)
    #Video_Name_List.append(name.text)
    #print(type(name.text))
#print(len(Video_Name_List))

#video_author = driver.find_elements_by_xpath("//a[1]//..//..//td[3]")
video_author = driver.find_elements_by_xpath("//table[3]//td[3]")
Video_Author_List = []
for author in video_author[:30]:
    Video_Author_List.append(author.text)
    #print(author.text)
#print(len(Video_Author_List))


video_date = driver.find_elements_by_xpath("//table[3]//td[5]")
Video_Date_List = []
for Date in video_date[:30]:
    Video_Date_List.append(Date.text)
    #print(Date.text)
#print(len(Video_Date_List))

video_views = driver.find_elements_by_xpath("//table[3]//td[4]")
Video_View_Count_List = []
for views in video_views[:30]:
    Video_View_Count_List.append(views.text)
    #print(views.text)
#print(len(Video_View_Count_List))

#creating the dataframe
df=pd.DataFrame({'Ranking':Video_Rank_List,
                 'Video Title':Video_Name_List,
                 'Artist/Creator':Video_Author_List, 
                 'Release Date': Video_Date_List, 
                 'Number Of Views': Video_View_Count_List})
#displaying the dataframe
df

,Ranking,Video Title,Artist/Creator,Release Date,Number Of Views
0,1,"""Baby Shark Dance",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",10.00
1,2,"""Despacito",Luis Fonsi,"January 12, 2017",7.70
2,3,"""Johny Johny Yes Papa""",LooLoo Kids,"October 8, 2016",6.10
3,4,"""Shape of You""",Ed Sheeran,"January 30, 2017",5.58
4,5,"""See You Again""",Wiz Khalifa,"April 6, 2015",5.38
5,6,"""Bath Song""",Cocomelon – Nursery Rhymes,"May 2, 2018",4.86
6,7,"""Learning Colors – Colorful Eggs on a Farm""",Miroshka TV,"February 27, 2018",4.55
7,8,"""Masha and the Bear – Recipe for Disaster""",Get Movies,"January 31, 2012",4.48
8,9,"""Uptown Funk""",Mark Ronson,"November 19, 2014",4.42
9,10,"""Phonics Song with Two Words""",ChuChu TV,"March 6, 2014",4.41
10,11,"""Gangnam Style""",Psy,"July 15, 2012",4.31
11,12,"""Dame Tu Cosita""",El Chombo,"April 5, 2018",3.80
12,13,"""Sugar""",Maroon 5,"January 14, 2015",3.62
13,14,"""Sorry""",Justin Bieber,"October 22, 2015",3.50
14,15,"""Roar""",Katy Perry,"September 5, 2013",3.50
15,16,"""Wheels on the Bus""",Cocomelon – Nursery Rhymes,"May 24, 2018",3.50
16,17,"""Counting Stars""",OneRepublic,"May 31, 2013",3.48
17,18,"""Thinking Out Loud""",Ed Sheeran,"October 7, 2014",3.39
18,19,"""Girls Like You""",Maroon 5,"May 31, 2018",3.21
19,20,"""Faded""",Alan Walker,"December 3, 2015",3.21
20,21,"""Dark Horse""",Katy Perry,"February 20, 2014",3.21
21,22,"""Axel F""",Crazy Frog,"June 16, 2009",3.17
22,23,"""Let Her Go""",Passenger,"July 25, 2012",3.15
23,24,"""Bailando""",Enrique Iglesias,"April 11, 2014",3.15
24,25,"""Lean On""",Major Lazer,"March 22, 2015",3.15
25,26,"""Shake It Off""",Taylor Swift,"August 18, 2014",3.13
26,27,"""Baa Baa Black Sheep""",Cocomelon – Nursery Rhymes,"June 25, 2018",3.07
27,28,"""Perfect""",Ed Sheeran,"November 9, 2017",3.06
28,29,"""Waka Waka (This Time for Africa)""",Shakira,"June 4, 2010",3.03
29,30,"""Mi Gente""",J Balvin,"June 29, 2017",3.03

#Question 2: #Print the details team India’s international fixtures from bcci.tv

In [100]:
#14/01
#import all the required libraries
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.action_chains import ActionChains

pd.options.display.max_colwidth = 200

#Initializing selenium webdriver

options = webdriver.ChromeOptions()
#we use chromedriver manager to reduce chance of errors due to mismatched chrome version
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.maximize_window()


driver.maximize_window()
#url = "https://www.bcci.tv/international/fixtures"
#driver.get(url) #loading the webpage
#driver.implicitly_wait(4) # waiting for the page to complete loading

url = "https://www.bcci.tv/"
driver.get(url) #loading the webpage
driver.implicitly_wait(4) # waiting for the page to complete loading

#Now we have to navigate to the reuquired web page (International Fixtures)
driver.get(driver.find_element_by_xpath("/html/body/div[13]/div/div[1]/div[2]/ul[1]/li[2]/a").get_attribute("href"))

visible = True
counter = 1
time.sleep(10)


#element = driver.find_element_by_xpath(".//div[@class = 'tab-inner-content']//button[@class = 'match-btn btn-red d-flex align-items-center justify-content-center mx-auto mt-3']")
element = driver.find_element_by_xpath(".//div[@class = 'sponsors-container sponsor-desktop sec-top-img']")
actions = ActionChains(driver)
actions.move_to_element(element).perform()

# Navigating to the "More Fixtures Button"
while visible == True:
    try:
        print(counter)
        counter = counter + 1
        actions.move_to_element(element).perform()
        time.sleep(4)
        print("sleep complete")
        More_Fixtures = driver.find_element_by_xpath(".//div[@class = 'col-lg-12 col-md-12 col-sm-12']/button")
        More_Fixtures.click()
    except:
        print("exception")
        visible = False

#Now we get the link to the pages for each individual match and store them in a list        
match_links = []
Match_Title = []
Match_Series = []
Match_Date_List = []
Match_Location = []
Match_Time_List = []

Matches_Cards = driver.find_elements_by_xpath(".//a[@class = 'match-center-btn ng-scope']")
for m in Matches_Cards:
    match_links.append(m.get_attribute('href'))

#print(len(match_links))
#print(match_links)

# extracting Match titles
Title = driver.find_elements_by_xpath(".//div[@class = 'fix-place ng-binding ng-scope']")
for t in Title:
    Match_Title.append(t.text.split('-')[0])

# extracting Series the Match belongs to
Series_List = driver.find_elements_by_xpath("//h5[2]/span[@class = 'ng-binding']")
for s in Series_List:
    Match_Series.append(s.text)
    
# extracting the day on which the match will be played   
Date_List = driver.find_elements_by_xpath(".//h5[@class = 'ng-binding']")
for d in Date_List:
    Match_Date_List.append(d.text)
    #print(d.text)

# extracting the time of the day on which the match will be played   
Time_List = driver.find_elements_by_xpath(".//h5[@class = 'text-right ng-binding']")
for t1 in Time_List:
    Match_Time_List.append(t1.text)
    #print(d.text)
    
#Extracting Location the Match will be played at
Location_List = driver.find_elements_by_xpath(".//div[@class = 'fix-place ng-binding ng-scope']")
for l in Location_List:
    Match_Location.append(l.text.split('-')[1])
    #print(l.text.split('-')[1])

#Creating the DataFrame
df = pd.DataFrame({'Match Date': Match_Date_List, 'Match Time': Match_Time_List, 'Match Title': Match_Title,
                   'Match Series Name': Match_Series, 'Match Location': Match_Location})
#Displaying the variables
df

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST driver version for 97.0.4692
Driver [C:\Users\Neil\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache

1
sleep complete
2
sleep complete
3
sleep complete
exception

,Match Date,Match Time,Match Title,Match Series Name,Match Location
0,15 JAN 2022,7:30 PM IST,,ICC MENS UNDER 19 WORLD CUP 2022,"Providence Stadium, Guyana"
1,19 JAN 2022,7:30 PM IST,,ICC MENS UNDER 19 WORLD CUP 2022,"Brian Lara Stadium, Trinidad"
2,19 JAN 2022,2:00 PM IST,1st ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl"
3,21 JAN 2022,2:00 PM IST,2nd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Boland Park, Paarl"
4,22 JAN 2022,7:30 PM IST,,ICC MENS UNDER 19 WORLD CUP 2022,"Brian Lara Stadium, Trinidad"
5,23 JAN 2022,2:00 PM IST,3rd ODI,INDIA TOUR OF SOUTH AFRICA ODI SERIES 2021/22,"Newlands, Cape Town"
6,6 FEB 2022,9:30 AM IST,1st ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"NARENDRA MODI STADIUM, Ahmedabad"
7,9 FEB 2022,9:30 AM IST,2nd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Sawai Mansingh Stadium, Jaipur"
8,12 FEB 2022,9:30 AM IST,3rd ODI,WEST INDIES TOUR OF INDIA ODI SERIES 2022,"Eden Gardens, Kolkata"
9,15 FEB 2022,7:30 PM IST,1st T20I,WEST INDIES TOUR OF INDIA T20 SERIES 2022,"Barabati Stadium, Cuttack"
10,18 FEB 2022,7:30 PM IST,2nd T20I,WEST INDIES TOUR OF INDIA T20 SERIES 2022,Dr YS Rajasekhara Reddy ACA
11,20 FEB 2022,7:30 PM IST,3rd T20I,WEST INDIES TOUR OF INDIA T20 SERIES 2022,"Greenfield International Stadium, Thiruvananthapuram"
12,25 FEB 2022,9:30 AM IST,1st Test,SRI LANKA TOUR OF INDIA TEST SERIES 2022,"M Chinnaswamy Stadium, Bengaluru"
13,5 MAR 2022,9:30 AM IST,2nd Test,SRI LANKA TOUR OF INDIA TEST SERIES 2022,"Punjab Cricket Association IS Bindra Stadium, Mohali"
14,13 MAR 2022,7:30 PM IST,1st T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022,"Punjab Cricket Association IS Bindra Stadium, Mohali"
15,15 MAR 2022,7:30 PM IST,2nd T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022,"Himachal Pradesh Cricket Association Stadium, Dharamsala"
16,18 MAR 2022,7:30 PM IST,3rd T20I,SRI LANKA TOUR OF INDIA T20 SERIES 2022,"Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow"
17,9 JUN 2022,7:30 PM IST,1st T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"MA Chidambaram Stadium, Chennai"
18,12 JUN 2022,7:30 PM IST,2nd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"M Chinnaswamy Stadium, Bengaluru"
19,14 JUN 2022,7:30 PM IST,3rd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Vidarbha Cricket Association Stadium, Nagpur"
20,17 JUN 2022,7:30 PM IST,4th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Saurashtra Cricket Association Stadium, Rajkot"
21,19 JUN 2022,7:30 PM IST,5th T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022,"Arun Jaitley Stadium, Delhi"

#Question 3: #Print the details of selenium exception from guru99.com.

In [36]:
#14/01
url = 'https://www.guru99.com/'
driver.get(url) #Loading the webpage
driver.implicitly_wait(4) # Waiting for the page to complete loading


#Navigating to the required page
driver.get(driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a").get_attribute("href"))
#driver.implicitly_wait(4)
driver.get(driver.find_element_by_xpath("/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a").get_attribute("href"))


#Initialising the variables to be used
Exception_Name_List = []
Exception_Description_List = []

#Populating the required variables
ExceptionName = driver.find_elements_by_xpath(".//table[@class = 'table table-striped']//tr/td[1]")
for Exception in ExceptionName[1:]:
    Exception_Name_List.append(Exception.text)

ExceptionDescription = driver.find_elements_by_xpath(".//table[@class = 'table table-striped']//tr/td[2]")
for i in ExceptionDescription[1:]:
    Exception_Description_List.append(i.text)
#creating and displaying the dataframe
df = pd.DataFrame({'Exception Name':Exception_Name_List, 'Exception Description': Exception_Description_List})
df

,Exception Name,Exception Description
0,ElementNotSelectableException,"This Selenium exception occurs when an element is presented in the DOM, but you can be able to select. Therefore, it is not possible to interact."
1,NoSuchElementException,This Exception occurs if an element could not be found.
2,NoSuchFrameException,This Exception occurs if the frame target to be switched to does not exist.
3,NoAlertPresentException,This Exception occurs when you switch to no presented alert.
4,NoSuchWindowException,This Exception occurs if the window target to be switch does not exist.
5,StaleElementReferenceException,This Selenium exception occurs happens when the web element is detached from the current DOM.
6,SessionNotFoundException,The WebDriver is acting after you quit the browser.
7,TimeoutException,"Thrown when there is not enough time for a command to be completed. For Example, the element searched wasn’t found in the specified time."
8,WebDriverException,This Exception takes place when the WebDriver is acting right after you close the browser.
9,ConnectionClosedException,This type of Exception takes place when there is a disconnection in the driver.
10,ElementClickInterceptedException,The command may not be completed as the element receiving the events is concealing the element which was requested clicked.
11,ElementNotInteractableException,"This Selenium exception is thrown when any element is presented in the DOM. However, it is impossible to interact with such an element."
12,ErrorInResponseException,This happens while interacting with the Firefox extension or the remote driver server.
13,ErrorHandler.UnknownServerException,Exception is used as a placeholder in case if the server returns an error without a stack trace.
14,ImeActivationFailedException,This expectation will occur when IME engine activation has failed.
15,ImeNotAvailableException,It takes place when IME support is unavailable.
16,InsecureCertificateException,Navigation made the user agent to hit a certificate warning. This can cause by an invalid or expired TLS certificate.
17,InvalidArgumentException,It occurs when an argument does not belong to the expected type.
18,InvalidCookieDomainException,This happens when you try to add a cookie under a different domain instead of current URL.
19,InvalidCoordinatesException,This type of Exception matches an interacting operation that is not valid.
20,InvalidElementStateExceptio,It occurs when command can’t be finished when the element is invalid.
21,InvalidSessionIdException,This Exception took place when the given session ID is not included in the list of active sessions. It means the session does not exist or is inactive either.
22,InvalidSwitchToTargetException,This occurs when the frame or window target to be switched does not exist.
23,JavascriptException,This issue occurs while executing JavaScript given by the user.
24,JsonException,It occurs when you afford to get the session when the session is not created.
25,NoSuchAttributeException,This kind of Exception occurs when the attribute of an element could not be found.
26,MoveTargetOutOfBoundsException,"It takes place if the target provided to the ActionChains move() methodology is not valid. For Example, out of the document."
27,NoSuchContextException,ContextAware does mobile device testing.
28,NoSuchCookieException,This Exception occurs when no cookie matching with the given pathname found for all the associated cookies of the currently browsing document.
29,NotFoundException,This Exception is a subclass of WebDriverException. This will occur when an element on the DOM does not exist.
30,RemoteDriverServerException,This Selenium exception is thrown when the server is not responding because of the problem that the capabilities described are not proper.
31,ScreenshotException,It is not possible to capture a screen.
32,SessionNotCreatedException,It happens when a new session could not be successfully created.
33,UnableToSetCookieException,This occurs if a driver is unable to set a cookie.
34,UnexpectedTagNameException,Happens if a support class did not get a web element as expected.
35,UnhandledAlertException,"This expectation occurs when there is an alert, but WebDriver is not able to perform Alert operation."
36,UnexpectedAlertPresentException,It occurs when there is the appearance of an unexpected alert.
37,UnknownMethodException,This Exception happens when the requested command matches with a known URL but and not matching with a methodology for a specific URL.
38,UnreachableBrowserException,This Exception occurs only when the browser is not able to be opened or crashed because of some reason.
39,UnsupportedCommandException,This occurs when remote WebDriver does n’t send valid commands as expected.

In [ ]:
#Question 4: # Print all the Indian state GDP details State-wise from statisticstime.com

In [6]:
#14/01
url = 'http://statisticstimes.com/'
driver.get(url) #Loading the webpage
driver.implicitly_wait(4) #waiting for the page to load
#Navigating to the required webpage
driver.get(driver.find_element_by_xpath("/html[1]/body[1]/div[2]/div[2]/div[1]/div[2]/p[2]/a[1]").get_attribute("href"))
driver.implicitly_wait(4)
driver.get(driver.find_element_by_xpath("//a[@href='country/india-gdp-growth.php']").get_attribute("href"))
driver.implicitly_wait(4)
driver.get(driver.find_element_by_xpath("//div[5]/ul[1]/li[6]/a[1]").get_attribute("href"))
driver.implicitly_wait(4)
driver.get(driver.find_element_by_xpath("//a[normalize-space()='» GDP of Indian states']").get_attribute("href"))

#Declaring the variables
State_Name_List = []
State_Rank_List = []
GSDPCPFY20 = []
GSDPCPFY19 = []
GDPSHARE1819 = []
State_GDP = []

#Populating the variables
for state in driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[2]"):
    #print(state.text)
    State_Name_List.append(state.text)
    
for rank in driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[1]"):
    #print(state.text)
    State_Rank_List.append(rank.text)

for gsdp20 in  driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[3]"):
    GSDPCPFY20.append(gsdp20.text)

for gsdp19 in driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[4]"):
    GSDPCPFY19.append(gsdp19.text)

for SHARE19 in driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[5]"):
    GDPSHARE1819.append(SHARE19.text)

for gdp in driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[6]"):
    State_GDP.append(gdp.text)
    
#driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[6]")
#driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[7]")
#driver.find_elements_by_xpath(".//div[5]/div[1]/div[1]/table[1]/tbody[1]//td[8]")

#Creating the DataFrame
df = pd.DataFrame({'State / UT Rank': State_Rank_List,
                   'State / UT Name': State_Name_List,
                   'GSDP at current price (19-20)':GSDPCPFY20,
                   'GSDP at current price (18-19)' : GSDPCPFY19,
                    '% Share of GDP': GDPSHARE1819,
                    'State GDP': State_GDP})
#Displaying the DataFrame
df

,State / UT Rank,State / UT Name,GSDP at current price (19-20),GSDP at current price (18-19),% Share of GDP,State GDP
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [3]:
#Question 5 : Print the details of trending repositories on Github.com

In [28]:
#14/01
url = 'https://github.com/'
driver.get(url) #Loading the Webpage
driver.implicitly_wait(4) #Waiting for the page to load

#Navigating to the requrired webpage
#driver.get(driver.find_element_by_xpath("//a[@href='/trending']").get_attribute("href"))
driver.get(driver.find_element_by_xpath("/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details/div/ul/li[5]/a").get_attribute("href"))
driver.implicitly_wait(4)

#Declaring the variables
Repo_Name_List = []
Repo_Description_List = []
Repo_Language_List = []
Number_Of_Contributors = []
Repo_Links_List = []
Repo_ContributorCount = []

#Populating the variable
for name in driver.find_elements_by_xpath("//h1[1]/a[1]"):
    Repo_Name_List.append(name.text) 
    

count_of_repositories_on_page = len(driver.find_elements_by_xpath("//h1[1]/a[1]"))
for dpe in range(0,count_of_repositories_on_page):
    LanguageUsedElement = '//article[' + str(dpe+1) + ']/div[2]/span[1]/span[2]'
    try:
        Repo_Language_List.append(driver.find_element_by_xpath(LanguageUsedElement).text)
    except:
        Repo_Language_List.append("-")

for link in driver.find_elements_by_xpath("//h1[1]/a[1]"):
    Repo_Links_List.append(link.get_attribute("href"))

for url in Repo_Links_List:
    driver.get(url)
    driver.implicitly_wait(4)
    try:
        Repo_ContributorCount.append(driver.find_element_by_xpath("//a[contains(text(),'Contributors')]//span").text)
    except:
        Repo_ContributorCount.append('N/A')
    
    try:
        Repo_Description_List.append(driver.find_element_by_xpath("//div[@class = 'BorderGrid-cell']/p").text)
    except:
        Repo_Description_List.append('N/A')
        

#declaring the DataFrame
df = pd.DataFrame({'Repository Titile':Repo_Name_List, 
                   'Repository Description': Repo_Description_List,
                   'Language Used': Repo_Language_List,
                   'Contributor Count': Repo_ContributorCount})
#Displaying the DataFrame
df

,Repository Titile,Repository Description,Language Used,Contributor Count
0,v4d1 / SpoofThatMail,Bash script to check if a domain or list of domains can be spoofed based in DMARC records,Shell,2
1,windowjs / windowjs,Window.js is an open-source Javascript runtime for desktop graphics programming.,C++,2
2,withastro / astro,"Build fast websites, faster. 🚀🧑‍🚀✨",TypeScript,216
3,CyC2018 / CS-Notes,📚 技术面试必备基础知识、Leetcode、计算机操作系统、计算机网络、系统设计,Java,231
4,apache / superset,Apache Superset is a Data Visualization and Data Exploration Platform,TypeScript,711
5,eugeneyan / applied-ml,📚 Papers & tech blogs by companies sharing their work on data science & machine learning in production.,-,34
6,cyrildiagne / ar-cutpaste,Cut and paste your surroundings using AR,TypeScript,6
7,abigsoft / jdog202201,京东2022炸年兽,C#,2
8,sottlmarek / DevSecOps,Ultimate DevSecOps library,-,13
9,facebookresearch / ConvNeXt,Code release for ConvNeXt model,Python,3
10,input-output-hk / plutus-apps,The Plutus application platform,Haskell,110
11,crater-invoice / crater,Open Source Invoicing Solution for Individuals & Businesses,PHP,66
12,MoienTajik / AspNetCore-Developer-Roadmap,Roadmap to becoming an ASP.NET Core developer in 2022,-,20
13,windowtoolbox / powershell-windows-toolbox,N/A,-,N/A
14,commit-live-students / Data_Science_Masters_Program_2021,N/A,Jupyter Notebook,N/A
15,itcharge / LeetCode-Py,⛽️「算法通关手册」，超详细的「算法与数据结构」基础讲解教程，「LeetCode」650+ 道题目 Python 版的详细解析。通过「算法理论学习」和「编程实战练习」相结合的方式，从零基础到彻底掌握算法知识。,Python,2
16,ethereumbook / ethereumbook,"Mastering Ethereum, by Andreas M. Antonopoulos, Gavin Wood",JavaScript,232
17,synercys / annotated_latex_equations,"Examples of how to create colorful, annotated equations in Latex using Tikz.",TeX,3
18,google / leveldb,LevelDB is a fast key-value storage library written at Google that provides an ordered mapping from string keys to string values.,C++,57
19,ultralytics / yolov5,YOLOv5 🚀 in PyTorch > ONNX > CoreML > TFLite,Python,203
20,input-output-hk / plutus-pioneer-program,N/A,Haskell,12
21,files-community / Files,A modern file manager that pushes the boundaries of the platform.,C#,167
22,alyssaxuu / omni,The all-in-one tool to supercharge your productivity ⌨️,JavaScript,4
23,QSCTech / zju-icicles,浙江大学课程攻略共享计划,HTML,86
24,prabhatsharma / zinc,"Zinc Search engine. A lightweight alternative to elasticsearch that requires minimal resources, written in Go.",Vue,10

In [29]:
print(len(Repo_Name_List))
print(len(Repo_Description_List))
print(len(Repo_Language_List))
print(len(Repo_ContributorCount))

25
25
25
25

In [4]:
# Question 6: Print the details of top 100 songs on billboard.com

In [21]:
#14/01
url = 'https://www.billboard.com/'

driver.get(url) #Loading the webpage
#driver.implicitly_wait(4) #waiting for the page to load

#Navigating to the requried webpage
#driver.get(driver.find_element_by_xpath("/html/body/div[2]/div[2]/div[2]/header/div/ul/li[1]/a").get_attribute("href"))
driver.get(driver.find_element_by_xpath("/html/body/div[4]/header/div[2]/div/nav/ul/li[1]/a").get_attribute("href"))
driver.implicitly_wait(4)

#Declaring the variables
Artist_name_List = []
Song_name_List = []
Rank_Last_Week_List = []
Peak_Rank_List = []
WeeksOnBoard_List = []

#Populating the Variables
Artist_name = driver.find_elements_by_xpath("//div[@class = 'o-chart-results-list-row-container']/ul/li[4]/ul/li[1]/span")
for a in Artist_name:
    Artist_name_List.append(a.text)
Song_name = driver.find_elements_by_xpath("//div[@class = 'o-chart-results-list-row-container']/ul/li[4]/ul/li[1]/h3")
for s in Song_name:
    Song_name_List.append(s.text)
Rank_Last_Week = driver.find_elements_by_xpath("//div[@class = 'o-chart-results-list-row-container']/ul/li[4]/ul/li[4]")
for r in Rank_Last_Week:
    Rank_Last_Week_List.append(r.text)

PeakRank = driver.find_elements_by_xpath("//div[@class = 'o-chart-results-list-row-container']/ul/li[4]/ul/li[5]")
for p in PeakRank:
    Peak_Rank_List.append(p.text)
WeeksOnBoard = driver.find_elements_by_xpath("//div[@class = 'o-chart-results-list-row-container']/ul/li[4]/ul/li[6]")
for w in WeeksOnBoard:
    WeeksOnBoard_List.append(w.text)

#Declaring the DataFrame
df = pd.DataFrame({'Artist Name': Artist_name_List, 'Song Name': Song_name_List,
                   'Rank Last Week':Rank_Last_Week_List,'Peak Rank':Peak_Rank_List,
                   'Weeks on Chart': WeeksOnBoard_List})
#Displaying the DataFrame
df

,Artist Name,Song Name,Rank Last Week,Peak Rank,Weeks on Chart
0,Adele,Easy On Me,2,1,13
1,The Kid LAROI & Justin Bieber,Stay,6,1,26
2,Glass Animals,Heat Waves,7,3,51
3,Ed Sheeran,Shivers,9,4,17
4,"Carolina Gaitan, Mauro Castillo, Adassa, Rhenzy Feliz, Diane Guerrero, Stephanie Beatriz & Encanto Cast",We Don't Talk About Bruno,50,5,2
...,...,...,...,...,...
95,"Nardo Wick, Lil Baby & Future",Me Or Sum,-,86,2
96,The Walters,I Love You So,-,97,1
97,Polo G,Bad Man (Smooth Criminal),-,49,6
98,Carly Pearce & Ashley McBryde,Never Wanted To Be That Girl,-,99,1
99,Priscilla Block,Just About Over You,-,81,7

In [ ]:
#Question 7: print the details of Data science recruiters from naukri.com

In [10]:
#14/01
#import all the required libraries
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.keys import Keys
pd.options.display.max_colwidth = 200
import random
#Initializing selenium webdriver

options = webdriver.ChromeOptions()
driver = webdriver.Chrome(ChromeDriverManager().install())
driver.maximize_window()

#Naukri
url = 'https://www.naukri.com/'
driver.get(url)
driver.implicitly_wait(4)

# Now we navigate to the Sitemap page
driver.get(driver.find_element_by_xpath("/html/body/div/div[2]/div[5]/div[1]/div/div/div[2]/ul/li[4]/a").get_attribute('href'))
time.sleep(3)

# Now we navigate to the recruiter listing page 
driver.get(driver.find_element_by_xpath("//ul[1]/li[2]/div[1]/ul[1]/li[1]/a[1]").get_attribute('href'))
JD = 'Data Science'

search_bar = driver.find_element_by_xpath("//input[@class = 'sugInp']")    # Locating search_bar by id

search_bar.send_keys(JD)     # sending user input to search bar
driver.implicitly_wait(1)
search_bar.send_keys(Keys.RETURN)

#search_button = driver.find_element_by_xpath("//button[@class = 'col search l2 btn btn-mid']")# Locating search_button by xpath
#search_button = driver.find_element_by_xpath("")# Locating search_button by xpath

#search_button.click()# Clicking the button to start search

# Now we initialise our variables
Recruiter_Name_List = []
Recruiter_Designation_List = []
Recruiter_Company_Name_List = []
Skills_Recruiting_For_List = []
Recruiter_Location_List = []
URL_List = []

page = 1
print('on page :', page)

# Extacting Recruiter Name
recruiter_names = driver.find_elements_by_xpath("//span[@class = 'fl ellipsis']")
#recruiter_names = driver.find_elements_by_xpath("//div[1]/div[1]/p[1]/a[1]/span[1]")
for recruiter in recruiter_names:
    Recruiter_Name_List.append(recruiter.text)

# Extacting Recruiter Designations
recruiter_designations = driver.find_elements_by_xpath("//span[@class = 'ellipsis clr']")
for designations in recruiter_designations:
    Recruiter_Designation_List.append(designations.text)

# Extacting Recruiter Company Name
Recruiter_Company_Name = driver.find_elements_by_xpath("//div[1]/div[1]/p[1]/a[2]")
for CompanyName in Recruiter_Company_Name:
    Recruiter_Company_Name_List.append(CompanyName.text)
    
# Extracting List of skills recruiter is looking for
for m in range(1,26):
    for n in range(1,3):
        temp_path1 = './html[1]/body[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[' + str(m) + ']/div[' + str(n) + ']/div[1]/div[2]'
                     #'//div[' + str(m) + ']/div[' + str(n) + ']/div[1]/div[2]'
        try:
            Skills_Recruiting_For_List.append(driver.find_element_by_xpath(temp_path1).text)
        except:
            Skills_Recruiting_For_List.append("N/A")

# Extacting Recruiter Location
for m in range(1,26):
    for n in range(1,3):
        temp_path2 = '//div[' + str(m) + ']/div[' + str(n) + ']/div[1]/div[1]/p/span[2]'
        try:
            Recruiter_Location_List.append(driver.find_element_by_xpath(temp_path2).text)
        except:
            Recruiter_Location_List.append("N/A")

#=============================================================================================================
# Now we go through the next pages to get the recruiter information on the next pages
search_button = driver.find_element_by_xpath("//button[@class = 'grayBtn']")
time.sleep(10)
search_button.click()

#i = True
#while i == True:
for k in range(1,3): #trying code for the first 3 pages
    try:
        search_button = driver.find_element_by_xpath(".//button[@class = 'grayBtn']//..//button[2]") #find next button
        search_button.click() #click next button
        n = random.randint(5,13)
        time.sleep(n)

        page = page + 1
        print('on page :', page)
        recruiter_names = driver.find_elements_by_xpath("//span[@class = 'fl ellipsis']")
        #recruiter_names = driver.find_elements_by_xpath("//div[1]/div[1]/p[1]/a[1]/span[1]")
        for recruiter in recruiter_names:
            Recruiter_Name_List.append(recruiter.text)

        recruiter_designations = driver.find_elements_by_xpath("//span[@class = 'ellipsis clr']")
        for designations in recruiter_designations:
            Recruiter_Designation_List.append(designations.text)

        Recruiter_Company_Name = driver.find_elements_by_xpath("//div[1]/div[1]/p[1]/a[2]")
        for CompanyName in Recruiter_Company_Name:
            Recruiter_Company_Name_List.append(CompanyName.text)

        #Skills_Recruiting_For = driver.find_elements_by_xpath("/html[1]/body[1]/div[3]/div[1]/div[2]/div[1]/div[2]//div[1]/div[2]")
        #Skills_Recruiting_For = driver.find_elements_by_xpath("//div[1]/div[1]/p[1]/a[1]/span[1]//..//..//..//..//div[2]")
        #Skills_Recruiting_For = driver.find_elements_by_xpath("//div[@class ='hireSec highlightable']")
        #for skills in Skills_Recruiting_For:
        #    Skills_Recruiting_For_List.append(skills.text)

        for m in range(1,26):
            for n in range(1,3):
                #temp_path1 = '//div[' + str(m) + ']/div[' + str(n) + ']/div[1]/div[1]/p/a[1]/span//..//..//span[2]'
                temp_path1 = './html[1]/body[1]/div[3]/div[1]/div[2]/div[1]/div[2]/div[' + str(m) + ']/div[' + str(n) + ']/div[1]/div[2]'
                try:
                    Skills_Recruiting_For_List.append(driver.find_element_by_xpath(temp_path1).text)
                except:
                    Skills_Recruiting_For_List.append("N/A")


        for m in range(1,26):
            for n in range(1,3):
                temp_path2 = '//div[' + str(m) + ']/div[' + str(n) + ']/div[1]/div[1]/p/span[2]'
                try:
                    Recruiter_Location_List.append(driver.find_element_by_xpath(temp_path2).text)
                except:
                    Recruiter_Location_List.append("N/A")

    except:
        i = False

print(len(Recruiter_Name_List))
print(len(Recruiter_Designation_List))
print(len(Recruiter_Company_Name_List))
print(len(Skills_Recruiting_For_List))
print(len(Recruiter_Location_List))

df = pd.DataFrame({'Recruiter Name':Recruiter_Name_List,'Designation': Recruiter_Designation_List,
                   'Company Name':Recruiter_Company_Name_List, 'Skills Recruiting for': Skills_Recruiting_For_List,
                   'Location':Recruiter_Location_List})
df

====== WebDriver manager ======
Current google-chrome version is 97.0.4692
Get LATEST driver version for 97.0.4692
Driver [C:\Users\Neil\.wdm\drivers\chromedriver\win32\97.0.4692.71\chromedriver.exe] found in cache

on page : 1
on page : 2
on page : 3
150
150
150
150
150

,Recruiter Name,Designation,Company Name,Skills Recruiting for,Location
0,Aakash Harit,HR Manager,Data Science Network,"Classic ASP Developer, Internet Marketing Professional, Data Science SME, Content Writers, SEO Professional, Revenue Professional",Delhi
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,".Net, Java, Data Science, Linux Administration, Sql Server Development, Winforms, Wcf Services, Wpf, Telecom Engineering, Technical Management, Software",Hyderabad / Secunderabad
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,"Data Science, Artificial Intelligence, Machine Learning, Business Analytics",Pune
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,"Mean Stack, javascript, angularjs, mongodb, Web Services, rest, express, Node.js, Big Data, iot, Data Science, Cloud Computing, saas, Aws",Ahmedabad
4,subhas patel,Founder CEO,LibraryXProject,"Hadoop, Spark, Digital Strategy, Data Architecture, Command Center, Cdp, Dmp, Kafka, Data Science, Data Analysis, Big Data Analytics, Real Time Analysis, SQL",UK - (london)
...,...,...,...,...,...
145,KIMS Hospitals,Company Recruiter,Krishna Institute of Medical Sciences Ltd.,"Techno Project Manager, Data Enablement, Data Science, Principal Architech, Project Manager, Pmo, Medical Transcription, Cso, Network Administration",Hyderabad / Secunderabad
146,Saibal Dhar,Company HR,abzooba,Not Specified,Kolkata
147,Sravan Kumar Ranga,Assistant Manager,GSPANN Technologies,"devops, build and release, Delivery Manager, Oracle Webcenter, selenium, ruby, hadoop, teamsite, java/j2ee, datastage, informatica, Production Support, core",Hyderabad / Secunderabad
148,Jagdish Gadkari,Founder and Managing Director,Spark Infotech,".Net Core, Data Science, Microsoft Azure, Microsoft Powerapps, Microsoft Power Bi",Mumbai
149,Lakshmi Prasanna,Company HR,Chiselon Technologies PVT LTD,"Java, Big Data, Data Science, Nlp, Qa Testing, Selenium, Javascript, Spring Boot, React.js, Angularjs, Net, Tableau, Mongodb, Cassandra, Cloud Computing",Hyderabad / Secunderabad

In [ ]:
#Question 8 : Print the details of Highest selling novels on theguardian.com

In [7]:
#14/01
url = 'https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare'
driver.get(url)
# then we wait while the page loads
driver.implicitly_wait(4)

#Initialinsing the variables
Book_Name_List = []
Author_Name_List = []
Units_Sold_List = []
Publisher_List = []
Genre_List = []

for name in driver.find_elements_by_xpath("//tbody[1]//td[2]"):
    Book_Name_List.append(name.text)
    
for author in driver.find_elements_by_xpath("//tbody[1]//td[3]"):
    Author_Name_List.append(author.text)

for sold in driver.find_elements_by_xpath("//tbody[1]//td[4]"):
    Units_Sold_List.append(sold.text)

for publisher in driver.find_elements_by_xpath("//tbody[1]//td[5]"):
    Publisher_List.append(publisher.text)
    
for genre in driver.find_elements_by_xpath("//tbody[1]//td[6]"):
    Genre_List.append(genre.text)

df = pd.DataFrame({'Book Name': Book_Name_List,'Author Name': Author_Name_List,
                   'Copies Sold': Units_Sold_List,'Publisher Name':Publisher_List,
                   'Genre':Genre_List})
# checking to see if the dataframe is proper
df

,Book Name,Author Name,Copies Sold,Publisher Name,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the Love of a Family","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to Cook in 24 Hours,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [ ]:
#Question 9 print the details of the most watched tv series of all time from imdb.com

In [8]:
#14/01
url = 'https://www.imdb.com/list/ls095964455/' #Loading the website
driver.get(url) #loading the website
driver.implicitly_wait(4) # waiting

#Initialinsing the variables
Name_List = []
Year_Span_List = []
Genre_List = []
Run_time_List = []
Ratings_List = []
Votes_List = []

#Populating the variables
for Series_Names in driver.find_elements_by_xpath("//div[2]/h3/a"):
    Name_List.append(Series_Names.text)
    
for Year_Span in driver.find_elements_by_xpath("//div[2]/h3/span[2]"):
    Year_Span_List.append(Year_Span.text)

for Genre in driver.find_elements_by_xpath("//div[2]/p[1]/span[5]"):
    Genre_List.append(Genre.text)
    
for Run_time in driver.find_elements_by_xpath("//div[2]/p[1]/span[3]"):
    Run_time_List.append(Run_time.text.split(' ')[0])

for Ratings in driver.find_elements_by_xpath("//div/div/span[@class = 'ipl-rating-star__star']//..//span[2]"):
    Ratings_List.append(Ratings.text)
    
for Votes in driver.find_elements_by_xpath("//div[2]/p[4]/span[2]"):
    Votes_List.append(Votes.text)

#Checking to confirm all elements are of the same length
print(len(Name_List))
print(len(Year_Span_List))
print(len(Genre_List))
print(len(Run_time_List))
print(len(Ratings_List))
print(len(Votes_List))

#creating the dataframe
df = pd.DataFrame({'Series Name': Name_List, 'Year Span': Year_Span_List,'Genre':Genre_List, 
                   'Run Time(in Minutes)':Run_time_List,'Ratings': Ratings_List,'Vote Count':Votes_List})
#displaying the dataframe
df

100
100
100
100
100
100

,Series Name,Year Span,Genre,Run Time(in Minutes),Ratings,Vote Count
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57,9.2,"1,930,901"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51,8.7,"951,671"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44,8.2,"922,287"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60,7.5,"276,348"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43,7.6,"236,594"
...,...,...,...,...,...,...
95,Reign,(2013–2017),"Drama, Fantasy",42,7.5,"47,189"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50,7.8,"57,981"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42,8.1,"183,063"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45,7.1,"38,343"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572,8.6,"218,058"

In [ ]:
#Question 10: Print the details of the Datasets from UCI machine learning repositories

In [5]:
#14/01
#print("started")
url = 'https://archive.ics.uci.edu/ml/index.php'
driver.get(url)
driver.implicitly_wait(4)
driver.get(driver.find_element_by_xpath("/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b//..//..").get_attribute("href"))
#print(driver.find_element_by_xpath("").get_attribute("href"))

Dataset_Name_List = []
Data_Type_List = []
Task_List = []
Attribute_Type_List = []
No_Of_Instances_List = []
No_Of_Attributes_List = []
Year_List = []

Dataset_Name_List = []
Data_Type_List = []   
Task_List = []        
Attribute_Type_List = []
No_Of_Instances_List = []
No_Of_Attributes_List = []
Year_List = []            

for name in driver.find_elements_by_xpath("//table[2]//b/a"):
    Dataset_Name_List.append(name.text)
    
for tasktype in driver.find_elements_by_xpath("//table[2]//td[2]//td[3]/p"):
    Task_List.append(tasktype.text)

for attributetype in driver.find_elements_by_xpath("//table[2]//td[2]//td[4]/p"):
    Attribute_Type_List.append(attributetype.text)
    
for instancecount in driver.find_elements_by_xpath("//table[2]//td[2]//td[5]/p"):
    No_Of_Instances_List.append(instancecount.text)

for attributecount in driver.find_elements_by_xpath("//table[2]//td[2]//td[6]/p"):
    No_Of_Attributes_List.append(attributecount.text)

for YearList in driver.find_elements_by_xpath("//table[2]//td[2]//td[7]/p"):
    Year_List.append(YearList.text)

for i in range(len(driver.find_elements_by_xpath("//table[2]//b/a"))):
    temp_path = '//tr[' + str(i + 2) + ']/td[2]/p[1]'
    Data_Type_List.append(driver.find_element_by_xpath(temp_path).text)

Task_List.pop(0)
Attribute_Type_List.pop(0)
No_Of_Instances_List.pop(0)
No_Of_Attributes_List.pop(0)
Year_List.pop(0)

print(len(Dataset_Name_List))
print(len(Data_Type_List))
print(len(Task_List))
print(len(Attribute_Type_List))
print(len(No_Of_Instances_List))
print(len(No_Of_Attributes_List))
print(len(Year_List))


df = pd.DataFrame({'Dataset Name': Dataset_Name_List, 'Data Type': Data_Type_List,'Task List': Task_List,
                   'Attribute Type': Attribute_Type_List, 'No Of Instances': No_Of_Instances_List,
                   'No_Of_Attributes_List':No_Of_Attributes_List,'Year Created': Year_List})
df

622
622
622
622
622
622
622

,Dataset Name,Data Type,Task List,Attribute Type,No Of Instances,No_Of_Attributes_List,Year Created
0,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
1,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
2,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
3,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
4,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
617,Influenza outbreak event prediction via Twitter data,Multivariate,Classification,"Integer, Real",75840,525,2020
618,Turkish Music Emotion Dataset,Multivariate,Classification,"Integer, Real",400,50,2020
619,Maternal Health Risk Data Set,,Classification,,1014,7,2020
620,Room Occupancy Estimation,"Multivariate, Time-Series",Classification,Real,10129,16,2021
621,Image Recognition Task Execution Times in Mobile Edge Computing,Univariate,Regression,Real,4000,2,2021

In [23]:


#Populating the variables
match_name = driver.find_elements_by_xpath("//strong[@class = 'fixture__name fixture__name--with-margin']")
for name in match_name:
    Match_Title.append(name.text)

match_date_time = driver.find_elements_by_xpath("//*[@class = 'fixture__full-date']")
for date in match_date_time:
    temp_date_time = date.text
    Match_Time_List.append(temp_date_time[-9:])
    Match_Date_List.append(temp_date_time[:-10].replace("\n", " "))

match_series = driver.find_elements_by_xpath("//span[@class = 'u-unskewed-text fixture__tournament-label u-truncated']")
for series in match_series:
    Match_Series.append(series.text)
    
match_location = driver.find_elements_by_xpath("//strong[@class = 'fixture__name fixture__name--with-margin']//..//span")
for location in match_location:
    Match_Location.append(location.text)

#Creating the DataFrame
df = pd.DataFrame({'Match Date': Match_Date_List, 'Match Time': Match_Time_List, 'Match Name': Match_Title,
                   'Match Series Name': Match_Series, 'Match Location': Match_Location})
#Displaying the variables
df

In [37]:
url = "https://www.bcci.tv/"
driver.get(url) #loading the webpage
driver.implicitly_wait(4) # waiting for the page to complete loading

#Now we have to navigate to the reuquired web page

driver.get(driver.find_element_by_xpath("/html/body/div[13]/div/div[1]/div[2]/ul[1]/li[2]/a").get_attribute("href"))


#Initialising the variables
Match_Date_List = []
Match_Time_List = []
Match_Title = []
Match_Series = []
Match_Location = []

visible = True

While visible == True:
    try:
        driver.find_element_by_xpath("//button[@class = 'match-btn btn-red d-flex align-items-center justify-content-center mx-auto mt-3']").click()
    except:
        visible = False

In [90]:
url = "https://www.bcci.tv/international/fixtures"
driver.get(url) #loading the webpage
driver.implicitly_wait(4) # waiting for the page to complete loading

#Now we have to navigate to the reuquired web page

#driver.get(driver.find_element_by_xpath("/html/body/div[13]/div/div[1]/div[2]/ul[1]/li[2]/a").get_attribute("href"))

visible = True
counter = 1
time.sleep(10)
more_fixtures = driver.find_element_by_xpath(".//div[@class = 'tab-inner-content']//button[@class = 'match-btn btn-red d-flex align-items-center justify-content-center mx-auto mt-3']")
#more_fixtures.click()
#time.sleep(10)
#driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
#more_fixtures.click()

In [ ]:
while visible == True:
    try:
        time.sleep(10)
        more_fixtures.click()
        print(counter)
        counter = counter + 1
    except:
        print("exception")
        visible = False

In [ ]:
for i in range(5):
    print("hi")
    time.sleep(10)
    more_fixtures = driver.find_element_by_xpath("//button[@class = 'match-btn btn-red d-flex align-items-center justify-content-center mx-auto mt-3']")
    more_fixtures.click()

In [76]:
print(more_fixtures.text)

More Fixtures

In [77]:
more_fixtures.click()

In [83]:
driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")

In [97]:
Matches = driver.find_elements_by_xpath("//div[@class = 'fixture-card ng-scope border-sky']/a")

In [99]:
for m in Matches:
    print(m.get_attribute("href"))